### PR TITLE
remove peerDependency o-topper

### PR DESCRIPTION
**Pull request by juanSanchezAlcala**
remove o-topper dependency from as it is not used in any part of the code and also it creates blocking issues due this unnecessary perDependency

### CODE REVIEW

**Review by umbobabo — APPROVED** [review]

**Review by fenglish — COMMENTED** [review]
It hasn't been removed from `package-lock.json`.

**Comment by juanSanchezAlcala** [comment]
> It hasn't been removed from `package-lock.json`.

Thank you, fix done

**Review by umbobabo — APPROVED** [review]

**Comment by juanSanchezAlcala** [comment]
> It hasn't been removed from `package-lock.json`.

fixed, thank you

**Review by fenglish — APPROVED** [review]
Thank you for tidying up @juanSanchezAlcala!

**Pull request merged**
